# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Lecture15-MapDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lecture15-MapDemo
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
	 
  target 'Lecture15-MapDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lecture15-MapDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
