# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'PuppyFlix' do
	pod 'TUSafariActivity', '~> 1.0'
	pod 'OHHTTPStubs'
	pod 'OHHTTPStubs/Swift'
end

target 'PuppyFlixTests' do
	pod 'OHHTTPStubs'
	pod 'OHHTTPStubs/Swift'
end

target 'PuppyFlixUITests' do
#	pod 'TUSafariActivity', '~> 1.0'
#	pod 'OHHTTPStubs'
#	pod 'OHHTTPStubs/Swift'
end

